Fix BannerPatternsDeserializer
Warzone/TGM pull request #728
Opened 2021-02-21 14:07 UTC by AtditC

Previously, the code checked if the returned PatternType Enum was null, however, this would always be false since if an Enum can't be find with .valueOf(), it will throw an exception. I used the EnumUtils to check if there is a PatternType Enum. If there isn't one, the code searches the PatternType by the identifier, just how it was already intended to work previously. This has also been tested on a CTF map.

2021-02-22 23:59 UTC, jorgeberrex requested changes

2021-02-22 23:59 UTC, jorgeberrex commented on TGM/src/main/java/network/warzone/tgm/parser/banner/BannerPatternsDeserializer.java
> +import org.bukkit.craftbukkit.libs.org.apache.commons.lang3.EnumUtils;
This is using a craftbukkit shaded library, please use `org.apache.commons.lang3.EnumUtils` instead

2021-02-22 23:59 UTC, jorgeberrex commented on TGM/src/main/java/network/warzone/tgm/parser/banner/BannerPatternsDeserializer.java
> +                        patternType = PatternType.getByIdentifier(jsonObject.get("type").getAsString());
Another nitpick, `jsonObject.get("type").getAsString()` is being called 3 times

2021-02-22 23:59 UTC, jorgeberrex commented on TGM/src/main/java/network/warzone/tgm/parser/banner/BannerPatternsDeserializer.java
> +                        patternType = PatternType.valueOf(Strings.getTechnicalName(args[1]));
Nitpick but since `Strings.getTechnicalName(args[1])` appears twice, perhaps store it in a local variable instead

2021-02-25 09:40 UTC, AtditC commented
I switched to the try/catch and also made a change which makes the "patterns" list in the flag json object optional. Flags don't necessarily need a pattern. Without this change, you would need to put an empty "patterns": [] in the flag object to get it to work.

2021-02-25 13:51 UTC, jorgeberrex approved these changes

2021-02-25 13:51 UTC, merged